In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv('./responses_raw.csv')
df = df.replace(np.nan, '', regex=True)

In [28]:
df['kindergarten_open_to_vital'] = df['open_to_vital'].str.contains('Kindergarten')
df['highschool_open_to_vital'] = df['open_to_vital'].str.contains('Highschool')
df['university_open_to_vital'] = df['open_to_vital'].str.contains('University')

In [29]:
categorical_array_columns = ['prohibited_all', 'open_to_vital', 'closed_to_everyone']

In [30]:
for category in categorical_array_columns:
    unique = np.unique([item for sublist in df[category].map(lambda x: (x.split(', '))).tolist() for item in sublist]).tolist()
    for key in unique:
        df_key = key.replace(' ', '_').lower() + "_" + category
        df[df_key] = df[category].str.contains(key)
        df[df_key] = df[df_key].astype(int)
df = df.drop(categorical_array_columns, axis=1)

/usr/local/Cellar/ipython/7.1.1/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """

In [31]:
categorical_columns = ['sufficient_protection', 'mentality_category']
df = pd.concat([df, pd.get_dummies(df['sufficient_protection'], prefix='protection')], 1)
df = df.drop(categorical_columns, axis=1)

In [32]:
df

,Timestamp,country,start_date,end_date,lockdown_severity,leasure_shopping_prohibited,maximum_together,mentality_grade,government_performance,kindergarten_open_to_vital,...,bars_closed_to_everyone,highschool_closed_to_everyone,kindergarten_closed_to_everyone,restaurants_closed_to_everyone,shops_other_than_supermarkets_closed_to_everyone,university_closed_to_everyone,protection_Not at all,protection_Only for any healthcare worker,protection_Only for hospital staff,protection_Sufficient for everyone
0,4/10/2020 14:03:47,Belgium,3/18/2020,,5.0,1,2,7.0,6.0,1,...,1,1,1,1,1,1,0,1,0,0
1,4/15/2020 12:15:09,Croatia,3/18/2020,,8.0,1,,8.0,9.0,1,...,1,1,1,1,1,1,0,0,0,1
2,4/10/2020 12:46:13,Curacao,3/29/2020,,8.0,1,2,4.0,6.0,1,...,1,1,1,1,1,1,0,0,1,0
3,4/24/2020 8:17:43,Denmark,3/11/2020,,5.0,1,10,3.0,5.0,0,...,0,0,0,0,0,0,0,0,0,1
4,4/10/2020 14:02:19,France,3/16/2020,,7.1,1,2,7.4,7.4,1,...,1,1,0,1,1,1,0,1,0,0
5,4/15/2020 12:02:17,Germany,3/20/2020,,6.0,1,2,7.0,8.0,1,...,1,0,0,1,1,0,0,1,0,0
6,4/10/2020 12:24:15,Ireland,3/24/2020,,6.8,1,3,7.8,8.8,0,...,1,1,1,1,1,1,0,1,0,0
7,4/10/2020 20:23:04,Israel,4/2/2020,,9.0,1,4,10.0,10.0,0,...,1,1,1,1,1,1,0,1,0,0
8,4/10/2020 14:02:19,Italy,3/10/2020,,8.0,1,1,8.0,6.4,0,...,1,1,1,1,1,1,1,0,0,0
9,4/25/2020 15:36:01,Japan,4/7/2020,,5.0,1,,5.0,4.0,1,...,1,1,1,0,0,1,0,0,1,0
10,4/10/2020 12:36:01,United Kingdom,3/23/2020,,7.0,1,2,7.5,7.0,1,...,1,1,0,1,1,1,0,0,1,0
11,4/10/2020 10:54:06,Netherlands,3/23/2020,,5.0,0,3,7.0,8.0,1,...,1,1,0,1,0,1,1,0,0,0
12,4/24/2020 7:53:23,North Macedonia,3/19/2020,4/4/2020,7.0,1,2,5.0,7.0,0,...,1,1,1,1,0,1,0,0,0,1
13,4/10/2020 12:46:22,Slovenia,3/16/2020,,7.5,1,2,8.0,8.0,0,...,1,1,1,1,1,1,0,0,1,0
14,4/10/2020 12:03:11,Switzerland,3/17/2020,,8.0,1,5,9.0,7.0,0,...,1,1,1,1,1,1,0,1,0,0
15,4/10/2020 14:02:19,Texas (Dallas),3/22/2020,,7.0,1,1,6.0,5.0,0,...,1,1,1,0,1,1,1,0,0,0
16,4/23/2020 18:32:39,Ukraine,3/15/2020,3/15/2020,5.7,1,2,5.3,4.4,0,...,1,1,1,1,1,1,0,0,0,1

In [33]:
country_info = pd.read_csv('../Yu/covid19_country_info.csv')
weather_info = pd.read_csv('../Yu/covid19_country_weather.csv')

In [34]:
df = df.merge(country_info,on='country')
df = df.merge(weather_info,on='country')
df

,Timestamp,country,start_date,end_date,lockdown_severity,leasure_shopping_prohibited,maximum_together,mentality_grade,government_performance,kindergarten_open_to_vital,...,apr_temp,may_temp,jun_temp,july_temp,aug_temp,sept_temp,oct_temp,nov_temp,dec_temp,annual_temp
0,4/10/2020 14:03:47,Belgium,3/18/2020,,5.0,1,2,7.0,6.0,1,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
1,4/15/2020 12:15:09,Croatia,3/18/2020,,8.0,1,,8.0,9.0,1,...,10.247004,14.759786,17.992071,20.039893,19.667285,16.355071,11.349611,5.959764,1.528573,10.470911
2,4/24/2020 8:17:43,Denmark,3/11/2020,,5.0,1,10,3.0,5.0,0,...,5.867971,10.773036,14.401786,15.891429,15.902357,13.007679,9.359057,4.942146,1.645598,7.818978
3,4/10/2020 14:02:19,France,3/16/2020,,7.1,1,2,7.4,7.4,1,...,9.096851,12.717758,16.097942,18.603865,18.228694,15.782718,11.746692,6.690055,3.865740,10.543722
4,4/15/2020 12:02:17,Germany,3/20/2020,,6.0,1,2,7.0,8.0,1,...,7.687484,12.273226,15.496893,17.188080,16.968642,13.902305,9.431784,4.270517,0.880768,8.504452
5,4/10/2020 12:24:15,Ireland,3/24/2020,,6.8,1,3,7.8,8.8,0,...,7.694678,10.073630,12.799054,14.526135,14.276838,12.459108,10.081162,6.610897,5.446403,9.107924
6,4/10/2020 20:23:04,Israel,4/2/2020,,9.0,1,4,10.0,10.0,0,...,18.818000,21.895714,24.751714,26.449429,26.681571,25.123857,22.219000,17.569286,13.401857,19.698000
7,4/10/2020 14:02:19,Italy,3/10/2020,,8.0,1,1,8.0,6.4,0,...,9.612692,13.777579,17.524698,20.305087,20.144344,17.185813,12.856856,8.012446,4.398412,11.500694
8,4/25/2020 15:36:01,Japan,4/7/2020,,5.0,1,,5.0,4.0,1,...,8.702060,13.524019,17.340918,21.338652,22.744000,18.757239,12.777206,7.053675,1.748080,10.362726
9,4/10/2020 12:36:01,United Kingdom,3/23/2020,,7.0,1,2,7.5,7.0,1,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
10,4/10/2020 10:54:06,Netherlands,3/23/2020,,5.0,0,3,7.0,8.0,1,...,7.562913,11.983563,14.721875,16.550938,16.639875,13.895625,10.347350,5.916237,3.490613,9.201738
11,4/24/2020 7:53:23,North Macedonia,3/19/2020,4/4/2020,7.0,1,2,5.0,7.0,0,...,9.233964,13.985727,17.421182,19.846727,19.731727,16.310454,10.784882,5.366073,0.732434,9.853518
12,4/10/2020 12:46:22,Slovenia,3/16/2020,,7.5,1,2,8.0,8.0,0,...,7.578856,12.163411,15.398967,17.378222,16.942333,13.865478,9.208933,3.580752,-0.791111,8.040211
13,4/10/2020 12:03:11,Switzerland,3/17/2020,,8.0,1,5,9.0,7.0,0,...,3.347776,7.440950,10.780000,13.034811,12.544911,10.136311,6.080744,1.052785,-1.959079,4.749057
14,4/23/2020 18:32:39,Ukraine,3/15/2020,3/15/2020,5.7,1,2,5.3,4.4,0,...,9.085106,15.090398,18.421490,19.950162,19.344385,14.776107,8.625605,2.807330,-1.976805,8.205566