In [49]:
import pandas as pd
import numpy as np

In [33]:
confirmed = pd.read_csv('../Zaida/time_series_covid19_confirmed_global.csv')
deaths = pd.read_csv('../Zaida/time_series_covid19_deaths_global.csv')
recovered = pd.read_csv('../Zaida/time_series_covid19_recovered_global.csv')

In [34]:
confirmed = confirmed.melt(id_vars=['Country/Region','Province/State','Lat','Long'],var_name="Date",value_name="Confirmed").sort_values(by=['Country/Region','Date'])
deaths = deaths.melt(id_vars=['Country/Region','Province/State','Lat','Long'],var_name="Date",value_name="Deaths").sort_values(by=['Country/Region','Date'])
recovered = recovered.melt(id_vars=['Country/Region','Province/State','Lat','Long'],var_name="Date",value_name="Recovered").sort_values(by=['Country/Region','Date'])

In [45]:
df = pd.merge(confirmed,deaths,on=['Country/Region','Province/State','Lat','Long','Date'])
df = pd.merge(df,recovered,on=['Country/Region','Province/State','Lat','Long','Date'])
df

,Country/Region,Province/State,Lat,Long,Date,Confirmed,Deaths,Recovered
0,Afghanistan,NaN,33.0,65.0,1/22/20,0,0,0
1,Afghanistan,NaN,33.0,65.0,1/23/20,0,0,0
2,Afghanistan,NaN,33.0,65.0,1/24/20,0,0,0
3,Afghanistan,NaN,33.0,65.0,1/25/20,0,0,0
4,Afghanistan,NaN,33.0,65.0,1/26/20,0,0,0
5,Afghanistan,NaN,33.0,65.0,1/27/20,0,0,0
6,Afghanistan,NaN,33.0,65.0,1/28/20,0,0,0
7,Afghanistan,NaN,33.0,65.0,1/29/20,0,0,0
8,Afghanistan,NaN,33.0,65.0,1/30/20,0,0,0
9,Afghanistan,NaN,33.0,65.0,1/31/20,0,0,0
10,Afghanistan,NaN,33.0,65.0,2/1/20,0,0,0
11,Afghanistan,NaN,33.0,65.0,2/10/20,0,0,0
12,Afghanistan,NaN,33.0,65.0,2/11/20,0,0,0
13,Afghanistan,NaN,33.0,65.0,2/12/20,0,0,0
14,Afghanistan,NaN,33.0,65.0,2/13/20,0,0,0
15,Afghanistan,NaN,33.0,65.0,2/14/20,0,0,0
16,Afghanistan,NaN,33.0,65.0,2/15/20,0,0,0
17,Afghanistan,NaN,33.0,65.0,2/16/20,0,0,0
18,Afghanistan,NaN,33.0,65.0,2/17/20,0,0,0
19,Afghanistan,NaN,33.0,65.0,2/18/20,0,0,0
20,Afghanistan,NaN,33.0,65.0,2/19/20,0,0,0
21,Afghanistan,NaN,33.0,65.0,2/2/20,0,0,0
22,Afghanistan,NaN,33.0,65.0,2/20/20,0,0,0
23,Afghanistan,NaN,33.0,65.0,2/21/20,0,0,0
24,Afghanistan,NaN,33.0,65.0,2/22/20,0,0,0
25,Afghanistan,NaN,33.0,65.0,2/23/20,0,0,0
26,Afghanistan,NaN,33.0,65.0,2/24/20,1,0,0
27,Afghanistan,NaN,33.0,65.0,2/25/20,1,0,0
28,Afghanistan,NaN,33.0,65.0,2/26/20,1,0,0
29,Afghanistan,NaN,33.0,65.0,2/27/20,1,0,0
...,...,...,...,...,...,...,...,...
26506,Zimbabwe,NaN,-20.0,30.0,4/16/20,23,3,1
26507,Zimbabwe,NaN,-20.0,30.0,4/17/20,24,3,2
26508,Zimbabwe,NaN,-20.0,30.0,4/18/20,25,3,2
26509,Zimbabwe,NaN,-20.0,30.0,4/19/20,25,3,2
26510,Zimbabwe,NaN,-20.0,30.0,4/2/20,9,1,0
26511,Zimbabwe,NaN,-20.0,30.0,4/20/20,25,3,2
26512,Zimbabwe,NaN,-20.0,30.0,4/21/20,28,3,2
26513,Zimbabwe,NaN,-20.0,30.0,4/22/20,28,4,2
26514,Zimbabwe,NaN,-20.0,30.0,4/23/20,28,4,2
26515,Zimbabwe,NaN,-20.0,30.0,4/24/20,29,4,2
26516,Zimbabwe,NaN,-20.0,30.0,4/25/20,31,4,2
26517,Zimbabwe,NaN,-20.0,30.0,4/26/20,31,4,2
26518,Zimbabwe,NaN,-20.0,30.0,4/27/20,32,4,5
26519,Zimbabwe,NaN,-20.0,30.0,4/28/20,32,4,5
26520,Zimbabwe,NaN,-20.0,30.0,4/29/20,32,4,5
26521,Zimbabwe,NaN,-20.0,30.0,4/3/20,9,1,0
26522,Zimbabwe,NaN,-20.0,30.0,4/30/20,40,4,5
26523,Zimbabwe,NaN,-20.0,30.0,4/4/20,9,1,0
26524,Zimbabwe,NaN,-20.0,30.0,4/5/20,9,1,0
26525,Zimbabwe,NaN,-20.0,30.0,4/6/20,10,1,0
26526,Zimbabwe,NaN,-20.0,30.0,4/7/20,11,2,0
26527,Zimbabwe,NaN,-20.0,30.0,4/8/20,11,3,0
26528,Zimbabwe,NaN,-20.0,30.0,4/9/20,11,3,0
26529,Zimbabwe,NaN,-20.0,30.0,5/1/20,40,4,5
26530,Zimbabwe,NaN,-20.0,30.0,5/2/20,34,4,5
26531,Zimbabwe,NaN,-20.0,30.0,5/3/20,34,4,5
26532,Zimbabwe,NaN,-20.0,30.0,5/4/20,34,4,5
26533,Zimbabwe,NaN,-20.0,30.0,5/5/20,34,4,5
26534,Zimbabwe,NaN,-20.0,30.0,5/6/20,34,4,5
26535,Zimbabwe,NaN,-20.0,30.0,5/7/20,34,4,5

In [77]:
extra_data_df = pd.read_csv("../country_info.csv")
extra_data_df["Country/Region"] = [country_name.replace("'","") for country_name in extra_data_df["country"]]
extra_data_df['Province/State'] = np.nan
extra_data_df = extra_data_df.drop(['country','Timestamp','ID'],axis=1)
extra_data_df['Province/State'] = extra_data_df['Province/State'].astype('object')
combined = pd.merge(df,extra_data_df,on=['Country/Region','Province/State'])

,Country/Region,Province/State,Lat,Long,Date,Confirmed,Deaths,Recovered,start_date,end_date,...,apr_temp,may_temp,jun_temp,july_temp,aug_temp,sept_temp,oct_temp,nov_temp,dec_temp,annual_temp
0,Belgium,NaN,50.8333,4.000,1/22/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
1,Belgium,NaN,50.8333,4.000,1/23/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
2,Belgium,NaN,50.8333,4.000,1/24/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
3,Belgium,NaN,50.8333,4.000,1/25/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
4,Belgium,NaN,50.8333,4.000,1/26/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
5,Belgium,NaN,50.8333,4.000,1/27/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
6,Belgium,NaN,50.8333,4.000,1/28/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
7,Belgium,NaN,50.8333,4.000,1/29/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
8,Belgium,NaN,50.8333,4.000,1/30/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
9,Belgium,NaN,50.8333,4.000,1/31/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
10,Belgium,NaN,50.8333,4.000,2/1/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
11,Belgium,NaN,50.8333,4.000,2/10/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
12,Belgium,NaN,50.8333,4.000,2/11/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
13,Belgium,NaN,50.8333,4.000,2/12/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
14,Belgium,NaN,50.8333,4.000,2/13/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
15,Belgium,NaN,50.8333,4.000,2/14/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
16,Belgium,NaN,50.8333,4.000,2/15/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
17,Belgium,NaN,50.8333,4.000,2/16/20,1,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
18,Belgium,NaN,50.8333,4.000,2/17/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
19,Belgium,NaN,50.8333,4.000,2/18/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
20,Belgium,NaN,50.8333,4.000,2/19/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
21,Belgium,NaN,50.8333,4.000,2/2/20,0,0,0,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
22,Belgium,NaN,50.8333,4.000,2/20/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
23,Belgium,NaN,50.8333,4.000,2/21/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
24,Belgium,NaN,50.8333,4.000,2/22/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
25,Belgium,NaN,50.8333,4.000,2/23/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
26,Belgium,NaN,50.8333,4.000,2/24/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
27,Belgium,NaN,50.8333,4.000,2/25/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
28,Belgium,NaN,50.8333,4.000,2/26/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
29,Belgium,NaN,50.8333,4.000,2/27/20,1,0,1,3/18/2020,NaN,...,8.145482,12.398000,15.434529,17.238529,17.183294,14.427412,10.678388,5.761971,3.113924,9.514241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1575,United Kingdom,NaN,55.3781,-3.436,4/16/20,103093,15944,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1576,United Kingdom,NaN,55.3781,-3.436,4/17/20,108692,16879,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1577,United Kingdom,NaN,55.3781,-3.436,4/18/20,114217,17994,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1578,United Kingdom,NaN,55.3781,-3.436,4/19/20,120067,18492,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1579,United Kingdom,NaN,55.3781,-3.436,4/2/20,33718,3747,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1580,United Kingdom,NaN,55.3781,-3.436,4/20/20,124743,19051,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1581,United Kingdom,NaN,55.3781,-3.436,4/21/20,129044,20223,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1582,United Kingdom,NaN,55.3781,-3.436,4/22/20,133495,21060,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1583,United Kingdom,NaN,55.3781,-3.436,4/23/20,138078,21787,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1584,United Kingdom,NaN,55.3781,-3.436,4/24/20,143464,22792,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1585,United Kingdom,NaN,55.3781,-3.436,4/25/20,148377,23635,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1586,United Kingdom,NaN,55.3781,-3.436,4/26/20,152840,24055,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1587,United Kingdom,NaN,55.3781,-3.436,4/27/20,157149,24393,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1588,United Kingdom,NaN,55.3781,-3.436,4/28/20,161145,25302,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1589,United Kingdom,NaN,55.3781,-3.436,4/29/20,165221,26097,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1590,United Kingdom,NaN,55.3781,-3.436,4/3/20,38168,4461,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1591,United Kingdom,NaN,55.3781,-3.436,4/30/20,171253,26771,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1592,United Kingdom,NaN,55.3781,-3.436,4/4/20,41903,5221,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1593,United Kingdom,NaN,55.3781,-3.436,4/5/20,47806,5865,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1594,United Kingdom,NaN,55.3781,-3.436,4/6/20,51608,6433,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1595,United Kingdom,NaN,55.3781,-3.436,4/7/20,55242,7471,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1596,United Kingdom,NaN,55.3781,-3.436,4/8/20,60733,8505,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1597,United Kingdom,NaN,55.3781,-3.436,4/9/20,65077,9608,135,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1598,United Kingdom,NaN,55.3781,-3.436,5/1/20,177454,27510,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1599,United Kingdom,NaN,55.3781,-3.436,5/2/20,182260,28131,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1600,United Kingdom,NaN,55.3781,-3.436,5/3/20,186599,28446,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1601,United Kingdom,NaN,55.3781,-3.436,5/4/20,190584,28734,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1602,United Kingdom,NaN,55.3781,-3.436,5/5/20,194990,29427,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1603,United Kingdom,NaN,55.3781,-3.436,5/6/20,201101,30076,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239
1604,United Kingdom,NaN,55.3781,-3.436,5/7/20,206715,30615,0,3/23/2020,NaN,...,6.742380,9.815439,12.765885,14.435399,14.286812,12.213888,9.472010,5.524062,3.849172,8.310239

In [78]:
df

,Country/Region,Province/State,Lat,Long,Date,Confirmed,Deaths,Recovered
0,Afghanistan,NaN,33.0,65.0,1/22/20,0,0,0
1,Afghanistan,NaN,33.0,65.0,1/23/20,0,0,0
2,Afghanistan,NaN,33.0,65.0,1/24/20,0,0,0
3,Afghanistan,NaN,33.0,65.0,1/25/20,0,0,0
4,Afghanistan,NaN,33.0,65.0,1/26/20,0,0,0
5,Afghanistan,NaN,33.0,65.0,1/27/20,0,0,0
6,Afghanistan,NaN,33.0,65.0,1/28/20,0,0,0
7,Afghanistan,NaN,33.0,65.0,1/29/20,0,0,0
8,Afghanistan,NaN,33.0,65.0,1/30/20,0,0,0
9,Afghanistan,NaN,33.0,65.0,1/31/20,0,0,0
10,Afghanistan,NaN,33.0,65.0,2/1/20,0,0,0
11,Afghanistan,NaN,33.0,65.0,2/10/20,0,0,0
12,Afghanistan,NaN,33.0,65.0,2/11/20,0,0,0
13,Afghanistan,NaN,33.0,65.0,2/12/20,0,0,0
14,Afghanistan,NaN,33.0,65.0,2/13/20,0,0,0
15,Afghanistan,NaN,33.0,65.0,2/14/20,0,0,0
16,Afghanistan,NaN,33.0,65.0,2/15/20,0,0,0
17,Afghanistan,NaN,33.0,65.0,2/16/20,0,0,0
18,Afghanistan,NaN,33.0,65.0,2/17/20,0,0,0
19,Afghanistan,NaN,33.0,65.0,2/18/20,0,0,0
20,Afghanistan,NaN,33.0,65.0,2/19/20,0,0,0
21,Afghanistan,NaN,33.0,65.0,2/2/20,0,0,0
22,Afghanistan,NaN,33.0,65.0,2/20/20,0,0,0
23,Afghanistan,NaN,33.0,65.0,2/21/20,0,0,0
24,Afghanistan,NaN,33.0,65.0,2/22/20,0,0,0
25,Afghanistan,NaN,33.0,65.0,2/23/20,0,0,0
26,Afghanistan,NaN,33.0,65.0,2/24/20,1,0,0
27,Afghanistan,NaN,33.0,65.0,2/25/20,1,0,0
28,Afghanistan,NaN,33.0,65.0,2/26/20,1,0,0
29,Afghanistan,NaN,33.0,65.0,2/27/20,1,0,0
...,...,...,...,...,...,...,...,...
26506,Zimbabwe,NaN,-20.0,30.0,4/16/20,23,3,1
26507,Zimbabwe,NaN,-20.0,30.0,4/17/20,24,3,2
26508,Zimbabwe,NaN,-20.0,30.0,4/18/20,25,3,2
26509,Zimbabwe,NaN,-20.0,30.0,4/19/20,25,3,2
26510,Zimbabwe,NaN,-20.0,30.0,4/2/20,9,1,0
26511,Zimbabwe,NaN,-20.0,30.0,4/20/20,25,3,2
26512,Zimbabwe,NaN,-20.0,30.0,4/21/20,28,3,2
26513,Zimbabwe,NaN,-20.0,30.0,4/22/20,28,4,2
26514,Zimbabwe,NaN,-20.0,30.0,4/23/20,28,4,2
26515,Zimbabwe,NaN,-20.0,30.0,4/24/20,29,4,2
26516,Zimbabwe,NaN,-20.0,30.0,4/25/20,31,4,2
26517,Zimbabwe,NaN,-20.0,30.0,4/26/20,31,4,2
26518,Zimbabwe,NaN,-20.0,30.0,4/27/20,32,4,5
26519,Zimbabwe,NaN,-20.0,30.0,4/28/20,32,4,5
26520,Zimbabwe,NaN,-20.0,30.0,4/29/20,32,4,5
26521,Zimbabwe,NaN,-20.0,30.0,4/3/20,9,1,0
26522,Zimbabwe,NaN,-20.0,30.0,4/30/20,40,4,5
26523,Zimbabwe,NaN,-20.0,30.0,4/4/20,9,1,0
26524,Zimbabwe,NaN,-20.0,30.0,4/5/20,9,1,0
26525,Zimbabwe,NaN,-20.0,30.0,4/6/20,10,1,0
26526,Zimbabwe,NaN,-20.0,30.0,4/7/20,11,2,0
26527,Zimbabwe,NaN,-20.0,30.0,4/8/20,11,3,0
26528,Zimbabwe,NaN,-20.0,30.0,4/9/20,11,3,0
26529,Zimbabwe,NaN,-20.0,30.0,5/1/20,40,4,5
26530,Zimbabwe,NaN,-20.0,30.0,5/2/20,34,4,5
26531,Zimbabwe,NaN,-20.0,30.0,5/3/20,34,4,5
26532,Zimbabwe,NaN,-20.0,30.0,5/4/20,34,4,5
26533,Zimbabwe,NaN,-20.0,30.0,5/5/20,34,4,5
26534,Zimbabwe,NaN,-20.0,30.0,5/6/20,34,4,5
26535,Zimbabwe,NaN,-20.0,30.0,5/7/20,34,4,5

In [79]:
import numpy
import matplotlib.pyplot as plt
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.

In [80]:
# fix random seed for reproducibility
numpy.random.seed(7)

In [90]:
dataframe = pandas.read_csv('../airline-passengers.csv', usecols=[1], engine='python')
dataset = dataframe.values
dataset = dataset.astype('float32')

In [91]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

In [94]:
# split into train and test sets
train_size = int(len(dataset) * 0.67)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))

96 48

In [96]:
def create_dataset(dataset, look_back=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-look_back-1):
		a = dataset[i:(i+look_back), 0]
		dataX.append(a)
		dataY.append(dataset[i + look_back, 0])
	return numpy.array(dataX), numpy.array(dataY)

In [101]:
# reshape into X=t and Y=t+1
look_back = 1
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)

In [102]:
# reshape input to be [samples, time steps, features]
trainX = numpy.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = numpy.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

In [103]:
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=100, batch_size=1, verbose=2)

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.